### ISSUE TITLE
Any coupon applied 2 times

### ISSUE THREAD

**Issue by Zykhatslover** [silvershop/silvershop-discounts#102]
Hi.

Anytime I create a coupon, everything works fine except the coupon is applied 2 times on the order.  This happens for every coupon types and on every product.

I'm using a fresh installation of SS4 by the way, I guess it comes from that but I'm not quite sure how to fix it.

**Comment by Zykhatslover** [comment]
Ok well, I found that it comes from the modifier I added in the yaml config.  I actually added it without really knowing what it does, is removing it ok ? 

`SilverShop\Model\Order:
    modifiers:
      - SilverShop\Discounts\Model\Modifiers\OrderDiscountModifier`

**Comment by wilr** [comment]
Yes it's probably already added so you're adding the modifier twice.
