### ISSUE TITLE
Discount not calculating correctly

### ISSUE THREAD

**Issue by stratus21-liam** [silvershop/silvershop-discounts#111]
I dont understand how its taking £20 off the order rather than £10? The rules are very simple.. deduct £10 from the entire orer?

![image](https://user-images.githubusercontent.com/55092385/173442263-0a0f9bf6-d90f-4dad-a8ec-738039852fec.png)

**Comment by wilr** [comment]
@wkdcode-liam it may be executing the modifier twice. Can you please provide more information about your coupon setup, Silvershop versions and if you can replicate on the demo site.
