### ISSUE TITLE
Coupon remove

### ISSUE THREAD

**Issue by ctx2002** [silvershop/silvershop-discounts#45]
Hi:
After applied a coupon code, the coupon form shows 2 buttons.

"Apply coupon" and "remove coupon".

if clicks on "Remove coupon", even coupon on admin area  removed.

How to duplicate:

1> create a coupon on discount -> coupon tab
2> buy some thing and go to checkout page.
3> apply coupon.
4> remove coupon.
5>go back to admin discount panel , and coupon just created was removed.

Also, how can i apply a coupon at same time show a discount? it seems coupon overwrite
discount price on checkout form.

**Comment by adrian-stein** [comment]
I also just noticed that clicking the "remove coupon" button on the CouponForm removes the Coupon from the CMS completely and not just from the order!!!

**Comment by adrian-stein** [comment]
It looks like this line might be the culprit. https://github.com/silvershop/silvershop-discounts/blob/master/code/extensions/DiscountedOrderExtension.php#L76
