### ISSUE TITLE
Discounts added to orders, when viewing in ModelAdmin

### ISSUE THREAD

**Issue by NobrainerWeb** [silvershop/silvershop-discounts#47]
We believe we have found a bug, that causes coupons to be applied to all orders viewed in backend/Orders modeladmin.
Can someone test and see if they get the same result please.

Steps to reproduce:
1. Log in as an administrator
2. Go to the frontend of shop
3. Add a product to cart
4. Go to checkout page and apply a coupon code - leave the page open
5. Now in a new tab, go and visit a order in backend - the selected coupon code is applied to the order

(Coupon percentage based, applies per item, only Product Types "Product")

**Comment by pmhou** [comment]
I can confirm the same bug.

**Comment by pmhou** [comment]
@NobrainerWeb  https://github.com/silvershop/silvershop-discounts/pull/49

**Comment by pmhou** [comment]
So the reverse happens after a discount period has expired. Orders that were **discounted** are missing the discount modifier when viewing the order.
