### ISSUE TITLE
GiftVoucherProduct Issues

### ISSUE THREAD

**Issue by vixen1975** [silvershop/silvershop-discounts#48]
I am having a few issues with using the Gift Vouchers, I am not sure if there is anything I need to add to config.yml to make it work correctly. Currently I have:

Order:
  modifiers:
    - 'OrderDiscountModifier'
CheckoutPage:
  steps:
    'membership': 'CheckoutStep_Membership'
    'contactdetails': 'CheckoutStep_ContactDetails'
    'shippingaddress': 'CheckoutStep_Address'
    'billingaddress': 'CheckoutStep_Address'
    'shippingmethod': 'CheckoutStep_ShippingMethod'
    'discount' : 'CheckoutStep_Discount'
    'paymentmethod': 'CheckoutStep_PaymentMethod'
    'summary': 'CheckoutStep_Summary'

**Some of the problems are:**
1. I get this error message: Cannot access property GiftVoucherProduct::$global_allow_purchase from line 38 of GiftVoucherProduct
2. Gift vouchers are not purchaseable. The database does not save the value in 'Allow product to be purchased'. If I try to add them to a cart I get an error that tells me they can't be purchased. Looing in the database the value for 'AllowPurchase' is 1
3. I also get the message that 'Form' is not an allowed action on GiftVoucherProduct_Controller

If I add this to GiftVoucherProduct:
private static $global_allow_purchase  = true;

And add 'Form' as an allowed action on the controller, the problems go away. So I am not sure if I have missed configuring something correctly to make it run without me having to modify the code.

**Comment by wilr** [comment]
Fixed with #52
