### ISSUE TITLE
DiscountedOrderExtension::removeDiscounts() hard deletes Discounts from DB

### ISSUE THREAD

**Issue by sanderha** [silvershop/silvershop-discounts#57]
Shouldnt ``` DiscountedOrderExtension::removeDiscounts() ``` simply remove discounts from that particular order? Instead it calls ``` DataList::removeAll() ``` which will hard delete the discounts from the DB. 

It should probably delete ```DiscountModifiers``` on the order instead.

**Comment by wilr** [comment]
@sanderha Good catch. Would you like to submit a PR and ensure that this is fixed.

**Comment by wilr** [comment]
@sanderha I have tested this on the latest master and it doesn't seem to delete the discount, it deletes the many_many relation from OrderItem -> Discount which is correct. See manyManyList::removeAll. I did some testing and I can't see the behaviour of deleting the Discount in the DB using the removeCoupon method. Please reopen if you can attach a test case or a PR.
