### ISSUE TITLE
Specific pricing error

### ISSUE THREAD

**Issue by sparkcom** [silvershop/silvershop-discounts#76]
Hello ,

got the following error. I am using SS4. Wonder if there is a way around it. 

[Recoverable Error] Argument 1 passed to SilverShop\Discounts\Model\SpecificPrice::filter() must be an instance of SilverStripe\ORM\DataList, instance of SilverStripe\ORM\UnsavedRelationList given, called in /home/xxx/vendor/silvershop/discounts/src/Extensions/ProductSpecificPricingExtension.php on line 37

**Comment by sparkcom** [comment]
Need to change 

 if ($specificprice = SpecificPrice::filter(
            $this->owner->SpecificPrices()
                ->filter("Price:LessThan", $price), Member::currentUser()
        )->first()) {

to 

 $list = SpecificPrice::get()->filter(  array('ProductID'=>$this->owner->ID, "Price:LessThan"=> $price ));
  if ($specificprice = SpecificPrice::filter(
           $list, Security::getCurrentUser()
        )->first())

**Comment by wilr** [comment]
Can you please set that up as a PR to be merged? Cheers. You probably need to check `$list->exists()` before doing the filter by member.

**Comment by wilr** [comment]
Merged! Thanks
