### ISSUE TITLE
ProductsDiscountConstraint::check leaves Version in stage mode if no products are found

### ISSUE THREAD

**Issue by wernerkrauss** [silvershop/silvershop-discounts#90]
https://github.com/silvershop/silvershop-discounts/blob/master/src/Extensions/Constraints/ProductsDiscountConstraint.php#L57 sets the reading mode to Stage, but returns without recreating the current mode..

Wrap in `Versioned::withVersionedMode()` instead

**Comment by wilr** [comment]
Thanks!
