### ISSUE TITLE
Is it maintained?

### ISSUE THREAD

**Issue by abstractk** [silvershop/silvershop-discounts#91]
Not sure if this module is maintained anymore or not. 
I'm getting a timeout error on loading `/admin/discounts` page. No errors in `dev/build`.

Silvershop code version - `^3@dev`
SilverStripe version - `4.3.0@stable`

**Comment by wilr** [comment]
@abstractk Yes, this is still maintained. Can you post your version of discount module?

**Comment by abstractk** [comment]
Thanks @wilr. I'm using `dev-master 0576947` of the discount module.

**Comment by wilr** [comment]
@abstractk Thanks, you'll see the discount admin works fine on the demo - https://demo.silvershop.io/admin/discounts/ so might be related to your setup. Please use the Slack channel for personal support.
