### ISSUE TITLE
Fix SS4 install via composer

### ISSUE THREAD

**Issue by madmatt** [silvershop/silvershop-discounts#95]
Same issue as silvershop/silvershop-comparison#9, this module has an unrestricted requirement for silvershop/core in the only released version (e.g. `1.3.0`), meaning that composer pulls that before checking `dev-master`.

For this one, just updating the `1.3.0` version with a new `1.3.1` that targets `silvershop/core <3` would suffice.

**Comment by wilr** [comment]
Tagged `1.3.2` and a `2.0.0`.
